### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by FireMasterK** [TeamPiped/Piped#103]
Streams:
```
hey -c 50 -n 500 http://127.0.0.1:8080/streams/6zBfVElmWfw

Summary:
  Total:        10.8712 secs
  Slowest:      2.7826 secs
  Fastest:      0.2908 secs
  Average:      1.0226 secs
  Requests/sec: 45.9929

  Total data:   14749105 bytes
  Size/request: 29498 bytes

Response time histogram:
  0.291 [1]     |
  0.540 [15]    |■■■
  0.789 [111]   |■■■■■■■■■■■■■■■■■■■■■■■■■
  1.038 [179]   |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  1.287 [101]   |■■■■■■■■■■■■■■■■■■■■■■■
  1.537 [44]    |■■■■■■■■■■
  1.786 [38]    |■■■■■■■■
  2.035 [9]     |■■
  2.284 [0]     |
  2.533 [1]     |
  2.783 [1]     |


Latency distribution:
  10% in 0.6454 secs
  25% in 0.7870 secs
  50% in 0.9775 secs
  75% in 1.2136 secs
  90% in 1.5255 secs
  95% in 1.6920 secs
  99% in 1.8485 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0003 secs, 0.2908 secs, 2.7826 secs
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:    0.0002 secs, 0.0000 secs, 0.0061 secs
  resp wait:    1.0219 secs, 0.2906 secs, 2.7824 secs
  resp read:    0.0001 secs, 0.0000 secs, 0.0050 secs

Status code distribution:
  [200] 500 responses
```

**Comment by FireMasterK** [comment]
Channels:
```
hey -c 50 -n 500 http://127.0.0.1:8080/channels/UCTkXRDQl0luXxVQrRQvWS6w

Summary:
  Total:        4.8909 secs
  Slowest:      0.7749 secs
  Fastest:      0.1528 secs
  Average:      0.4580 secs
  Requests/sec: 102.2313

  Total data:   5154500 bytes
  Size/request: 10309 bytes

Response time histogram:
  0.153 [1]     |
  0.215 [4]     |■
  0.277 [7]     |■
  0.339 [24]    |■■■■■
  0.402 [76]    |■■■■■■■■■■■■■■■
  0.464 [199]   |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.526 [101]   |■■■■■■■■■■■■■■■■■■■■
  0.588 [43]    |■■■■■■■■■
  0.650 [19]    |■■■■
  0.713 [15]    |■■■
  0.775 [11]    |■■


Latency distribution:
  10% in 0.3683 secs
  25% in 0.4073 secs
  50% in 0.4425 secs
  75% in 0.4922 secs
  90% in 0.5839 secs
  95% in 0.6593 secs
  99% in 0.7700 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0001 secs, 0.1528 secs, 0.7749 secs
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:    0.0001 secs, 0.0000 secs, 0.0050 secs
  resp wait:    0.4577 secs, 0.1520 secs, 0.7741 secs
  resp read:    0.0001 secs, 0.0000 secs, 0.0005 secs

Status code distribution:
  [200] 500 responses
```

**Comment by mauriceoegerli** [comment]
Have you used a local backend or your instance?

**Comment by FireMasterK** [comment]
A local backend, but I reckon it would be a lot higher on an instance as they are all 1gbps.

**Comment by mauriceoegerli** [comment]
i tried the channels one too (locally)
hey -c 50 -n 500 http://127.0.0.1:8080/channels/UCTkXRDQl0luXxVQrRQvWS6w

Summary:
  Total:        1.6622 secs
  Slowest:      0.3577 secs
  Fastest:      0.1040 secs
  Average:      0.1552 secs
  Requests/sec: 300.8046

  Total data:   5154500 bytes
  Size/request: 10309 bytes

Response time histogram:
  0.104 [1]     |
  0.129 [154]   |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.155 [200]   |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.180 [83]    |■■■■■■■■■■■■■■■■■
  0.205 [12]    |■■
  0.231 [4]     |■
  0.256 [1]     |
  0.282 [10]    |■■
  0.307 [7]     |■
  0.332 [19]    |■■■■
  0.358 [9]     |■■


Latency distribution:
  10% in 0.1155 secs
  25% in 0.1258 secs
  50% in 0.1396 secs
  75% in 0.1585 secs
  90% in 0.2136 secs
  95% in 0.3126 secs
  99% in 0.3400 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0002 secs, 0.1040 secs, 0.3577 secs
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:    0.0001 secs, 0.0000 secs, 0.0021 secs
  resp wait:    0.1549 secs, 0.1039 secs, 0.3550 secs
  resp read:    0.0001 secs, 0.0000 secs, 0.0003 secs

Status code distribution:
  [200] 500 responses

**Comment by FireMasterK** [comment]
Very interesting, what did you see in your logs? (You only got error 500s)

**Comment by mauriceoegerli** [comment]
no, i got 200s, just 500 of them :D

**Comment by mauriceoegerli** [comment]
what ide do you use?

**Comment by FireMasterK** [comment]
> no, i got 200s, just 500 of them :D

Oh lol I just misread it 🤣

> what ide do you use?

I use eclipse but Intellij works great too

**Comment by mauriceoegerli** [comment]
```
java.net.ConnectException: Connection timed out: no further information
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:561)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at me.kavin.piped.utils.CaptchaSolver.createTask(CaptchaSolver.java:51)
        at me.kavin.piped.utils.CaptchaSolver.solve(CaptchaSolver.java:25)
        at me.kavin.piped.utils.DownloaderImpl.execute(DownloaderImpl.java:94)
        at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:70)
        at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:54)
        at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.isHardcodedClientVersionValid(YoutubeParsingHelper.java:280)
        at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getClientVersion(YoutubeParsingHelper.java:353)
        at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonResponse(YoutubeParsingHelper.java:659)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.onFetchPage(YoutubeChannelExtractor.java:85)
```
I think youtube didnt like that

**Comment by FireMasterK** [comment]
Wow you literally got a speed 3x faster than me, What's your internet speed?

**Comment by mauriceoegerli** [comment]
1gb/s
![grafik](https://user-images.githubusercontent.com/15955392/112873612-2690a180-90c2-11eb-8d8b-4906810f85aa.png)

**Comment by Jaedotmoe** [comment]
Here is mine.
```
➜  ~ hey -c 50 -n 500 https://piped.jae.fi/channels/UCTkXRDQl0luXxVQrRQvWS6w

Summary:
  Total:        0.1587 secs
  Slowest:      0.0895 secs
  Fastest:      0.0008 secs
  Average:      0.0119 secs
  Requests/sec: 3149.9059
  
  Total data:   1444500 bytes
  Size/request: 2889 bytes

Response time histogram:
  0.001 [1]     |
  0.010 [302]   |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.019 [98]    |■■■■■■■■■■■■■
  0.027 [52]    |■■■■■■■
  0.036 [9]     |■
  0.045 [28]    |■■■■
  0.054 [1]     |
  0.063 [2]     |
  0.072 [2]     |
  0.081 [0]     |
  0.090 [5]     |■


Latency distribution:
  10% in 0.0019 secs
  25% in 0.0034 secs
  50% in 0.0068 secs
  75% in 0.0138 secs
  90% in 0.0266 secs
  95% in 0.0400 secs
  99% in 0.0872 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0013 secs, 0.0008 secs, 0.0895 secs
  DNS-lookup:   0.0002 secs, 0.0000 secs, 0.0022 secs
  req write:    0.0000 secs, 0.0000 secs, 0.0009 secs
  resp wait:    0.0105 secs, 0.0007 secs, 0.0755 secs
  resp read:    0.0000 secs, 0.0000 secs, 0.0006 secs

Status code distribution:
  [200] 500 responses
```
