### ISSUE TITLE
SQL exception when creating/adding videos to playlists

### ISSUE THREAD

**Issue by leepfrog-ger** [TeamPiped/Piped#1155]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Somewhere during the last 2-6 weeks in my local instance (running on docker compose with compose files built through the piped configure scripts.) interactions with playlists have stopped working. 

Adding new playlists or adding videos to  playlists result in an SQL exception shown as browser popup. Accessing existing playlists and items within them work fine.

### To Reproduce

1. Log in to local piped instance
2. Click the "+" icon next to any video
3. Select the desired destination playlist from the dropdown and click `Add to playlist`

OR

1. Login to local piped instance
2. Click on `Playlists`
3. Click on `Create Playlist`
4. Choose any name and submit

### Expected behavior

Action is successful without error

### Logs/Errors

Trying to create a new playlist:

```
postgres         | 2022-06-25 11:14:43.904 UTC [28] ERROR:  column "playlist_id" is of type uuid but expression is of type bytea at character 96
postgres         | 2022-06-25 11:14:43.904 UTC [28] HINT:  You will need to rewrite or cast the expression.
postgres         | 2022-06-25 11:14:43.904 UTC [28] STATEMENT:  insert into playlists (name, owner, playlist_id, short_description, thumbnail) values ($1, $2, $3, $4, $5)
postgres         |      RETURNING *
piped-backend    | Jun 25, 2022 11:14:43 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
piped-backend    | WARN: SQL Error: 0, SQLState: 42804
piped-backend    | Jun 25, 2022 11:14:43 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
piped-backend    | ERROR: ERROR: column "playlist_id" is of type uuid but expression is of type bytea
piped-backend    |   Hint: You will need to rewrite or cast the expression.
piped-backend    |   Position: 96
piped-backend    | An error occoured in the path: /user/playlists/create
piped-backend    | jakarta.persistence.PersistenceException: Converting `org.hibernate.exception.SQLGrammarException` to JPA `PersistenceException` : could not execute statement
piped-backend    |      at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:165)
piped-backend    |      at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:175)
piped-backend    |      at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:182)
piped-backend    |      at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1424)
piped-backend    |      at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:474)
piped-backend    |      at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2232)
piped-backend    |      at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1928)
piped-backend    |      at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
piped-backend    |      at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
piped-backend    |      at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
piped-backend    |      at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
piped-backend    |      at me.kavin.piped.utils.ResponseHelper.createPlaylist(ResponseHelper.java:1004)
piped-backend    |      at me.kavin.piped.ServerLauncher.lambda$mainServlet$33(ServerLauncher.java:296)
piped-backend    |      at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)
piped-backend    |      at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250)
piped-backend    |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
piped-backend    |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
piped-backend    |      at java.base/java.lang.Thread.run(Unknown Source)
piped-backend    | Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
piped-backend    |      at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:89)
piped-backend    |      at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
piped-backend    |      at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
piped-backend    |      at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
piped-backend    |      at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
piped-backend    |      at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:57)
piped-backend    |      at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:42)
piped-backend    |      at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3276)
piped-backend    |      at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3886)
piped-backend    |      at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:80)
piped-backend    |      at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:612)
piped-backend    |      at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:483)
piped-backend    |      at java.base/java.util.LinkedHashMap.forEach(Unknown Source)
piped-backend    |      at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:480)
piped-backend    |      at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:329)
piped-backend    |      at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
piped-backend    |      at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
piped-backend    |      at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1420)
piped-backend    |      ... 14 more
piped-backend    | Caused by: org.postgresql.util.PSQLException: ERROR: column "playlist_id" is of type uuid but expression is of type bytea
piped-backend    |   Hint: You will need to rewrite or cast the expression.
piped-backend    |   Position: 96
piped-backend    |      at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
piped-backend    |      at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
piped-backend    |      at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
piped-backend    |      at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
piped-backend    |      at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
piped-backend    |      at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
piped-backend    |      at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:149)
piped-backend    |      at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
piped-backend    |      at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
piped-backend    |      at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
piped-backend    |      ... 27 more
```

triyng to add a video to an existing playlist:

```
piped-backend    | Jun 25, 2022 11:22:04 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
piped-backend    | WARN: SQL Error: 0, SQLState: 42883
piped-backend    | Jun 25, 2022 11:22:04 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
piped-backend    | ERROR: ERROR: operator does not exist: uuid = bytea
piped-backend    |   Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
piped-backend    |   Position: 436
piped-backend    | An error occoured in the path: /user/playlists/add
piped-backend    | jakarta.persistence.PersistenceException: Converting `org.hibernate.exception.SQLGrammarException` to JPA `PersistenceException` : JDBC exception executing SQL [select p1_0.id,p1_0.name,o1_0.id,o1_0.password,o1_0.session_id,o1_0.username,p1_0.playlist_id,p1_0.short_description,p1_0.thumbnail,v1_0.Playlist_id,v1_0.videos_order,v1_1.id,v1_1.uploader_id,v1_1.duration,v1_1.thumbnail,v1_1.title from playlists p1_0 left join (playlists_videos_ids v1_0 join playlist_videos v1_1 on v1_1.id=v1_0.videos_id) on p1_0.id=v1_0.Playlist_id left join users o1_0 on o1_0.id=p1_0.owner where p1_0.playlist_id=?]
piped-backend    |      at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:165)
piped-backend    |      at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:374)
piped-backend    |      at org.hibernate.query.sqm.internal.QuerySqmImpl.list(QuerySqmImpl.java:986)
piped-backend    |      at org.hibernate.query.spi.AbstractSelectionQuery.uniqueResult(AbstractSelectionQuery.java:451)
piped-backend    |      at org.hibernate.query.sqm.internal.QuerySqmImpl.uniqueResult(QuerySqmImpl.java:1010)
piped-backend    |      at me.kavin.piped.utils.ResponseHelper.addToPlaylistResponse(ResponseHelper.java:1164)
piped-backend    |      at me.kavin.piped.ServerLauncher.lambda$mainServlet$35(ServerLauncher.java:311)
piped-backend    |      at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)
piped-backend    |      at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250)
piped-backend    |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
piped-backend    |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
piped-backend    |      at java.base/java.lang.Thread.run(Unknown Source)
piped-backend    | Caused by: org.hibernate.exception.SQLGrammarException: JDBC exception executing SQL [select p1_0.id,p1_0.name,o1_0.id,o1_0.password,o1_0.session_id,o1_0.username,p1_0.playlist_id,p1_0.short_description,p1_0.thumbnail,v1_0.Playlist_id,v1_0.videos_order,v1_1.id,v1_1.uploader_id,v1_1.duration,v1_1.thumbnail,v1_1.title from playlists p1_0 left join (playlists_videos_ids v1_0 join playlist_videos v1_1 on v1_1.id=v1_0.videos_id) on p1_0.id=v1_0.Playlist_id left join users o1_0 on o1_0.id=p1_0.owner where p1_0.playlist_id=?]
piped-backend    |      at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:89)
piped-backend    |      at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
piped-backend    |      at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
piped-backend    |      at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
piped-backend    |      at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:253)
piped-backend    |      at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:146)
piped-backend    |      at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.lambda$processNext$0(JdbcValuesResultSetImpl.java:89)
piped-backend    |      at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advance(JdbcValuesResultSetImpl.java:274)
piped-backend    |      at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:85)
piped-backend    |      at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:29)
piped-backend    |      at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:89)
piped-backend    |      at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:142)
piped-backend    |      at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:32)
piped-backend    |      at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:437)
piped-backend    |      at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166)
piped-backend    |      at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91)
piped-backend    |      at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
piped-backend    |      at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:102)
piped-backend    |      at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:305)
piped-backend    |      at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:246)
piped-backend    |      at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:536)
piped-backend    |      at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363)
piped-backend    |      ... 10 more
piped-backend    | Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = bytea
piped-backend    |   Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
piped-backend    |   Position: 436
piped-backend    |      at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
piped-backend    |      at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
piped-backend    |      at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
piped-backend    |      at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
piped-backend    |      at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
piped-backend    |      at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
piped-backend    |      at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
piped-backend    |      at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
piped-backend    |      at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
piped-backend    |      at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:217)
piped-backend    |      ... 27 more
```

**Comment by LivingWithHippos** [comment]
it's an issue related to the backend  https://github.com/TeamPiped/Piped-Backend. The file https://github.com/TeamPiped/Piped-Backend/blob/master/src/main/java/me/kavin/piped/utils/obj/db/Playlist.java had its dependency change With commit [c23805288fe90282c7072a49456931e939e5291e](https://github.com/TeamPiped/Piped-Backend/commit/c23805288fe90282c7072a49456931e939e5291e) from javax.persistence to jakarta.persistence maybe that's  the problem

this is the lines that are probably exploding when adding a video to a playlist

https://github.com/TeamPiped/Piped-Backend/blob/c8628dcf0587718282c6b9fbf6eafb1922af3d4c/src/main/java/me/kavin/piped/utils/ResponseHelper.java#L1201-L1202

**Comment by LivingWithHippos** [comment]
I changed the db folder in the docker compose file so it got recreated with the new uudi format and it works again. I had exported and reimported my subscriptions but there is no option to do that with playlists if I'm not wrong

**Comment by leepfrog-ger** [comment]
I solved this for now by performing the following steps on the database:

- add a new column `playlist_id2` to the playlists table (Type BYTEA)
- Performed and UPDATE query that converts the `playlist_id` column content to BYTEA and write it to `playlist_id2`
- renamed column `playlist_id` to `playlist_id_old`
- renamed column `playlist_id2` to `playlist_id`

After this everything works as expected again

**Comment by FireMasterK** [comment]
For instances that still have this issue, you can run these commands to fix it:

```
docker exec -u postgres -it postgres psql -U piped
ALTER TABLE playlists ALTER COLUMN playlist_id TYPE uuid USING CAST(ENCODE(playlist_id, 'hex') AS uuid);
```

**Comment by leepfrog-ger** [comment]
Thanks, I can confirm it works with the most recent builds and the change reverted
