### ISSUE TITLE
Specific playlist does not work

### ISSUE THREAD

**Issue by FireMasterK** [TeamPiped/Piped#1255]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

The playlist https://piped.kavin.rocks/playlist?list=RDCLAK5uy_mqS2vPtJPBzKaS_TeSc5mDZIaMRFo-_pc does not work.

### To Reproduce

1. Open https://piped.kavin.rocks/playlist?list=RDCLAK5uy_mqS2vPtJPBzKaS_TeSc5mDZIaMRFo-_pc
2. Observe bug

### Expected behavior

The playlist should work, like on NewPipe.

### Logs/Errors

```
org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "The playlist does not exist."
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.defaultAlertsCheck(YoutubeParsingHelper.java:1403)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.onFetchPage(YoutubePlaylistExtractor.java:76)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:68)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:62)
	at me.kavin.piped.utils.ResponseHelper.playlistYouTubeResponse(ResponseHelper.java:369)
	at me.kavin.piped.utils.ResponseHelper.playlistResponse(ResponseHelper.java:328)
	at me.kavin.piped.ServerLauncher.lambda$mainServlet$13(ServerLauncher.java:137)
	at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)
	at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by the4anoni** [comment]
https://piped.kavin.rocks/playlist?list=PL6T-wOsBCQccPn2QSjgUSU8lKvbBv0NCN

I have same issue with playlist above

**Comment by IkelAtomig** [comment]
@FireMasterK - Your playlist does not exist.

@the4anoni - I can load yours.

**Comment by the4anoni** [comment]
> @FireMasterK - Your playlist does not exist.
> 
> @the4anoni - I can load yours.

It didn't worked before, but now it works for me too.
