### ISSUE TITLE
Datatype length issue

### ISSUE THREAD

**Issue by matt-laird** [TeamPiped/Piped#1635]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Preface, logging issue on frontend repo for a backend issue... Only place to log issues. I have not marked the `Can the bug be reproduced on the official instance?` because I can't see the backend logs, hence can't say.

### To Reproduce

1. Open Feed
2. Allow a feed item to be encountered
3. Observe Java error in backend.

### Expected behavior

Capture and store data on the backend without error.

### Logs/Errors

`ERROR: HHH000315: Exception executing batch [java.sql.BatchUpdateException: Batch entry 0 insert into videos (uploader_id, duration, is_short, thumbnail, title, uploaded, views, id) values ('UC_ViSsVg_3JUDyLS3E2Un5g', 2060, 'FALSE', 'https://i.ytimg.com/vi/0k28PAgFpGA/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGEgYShhMA8=&rs=AOn4CLDMg7ubsKkmB2-p2PJwXPrrtxJuuQ', 'ATM7 Skyblock Ep42 FTB Industrial Contraptions', 1667041202000, 60, '0k28PAgFpGA') was aborted: ERROR: value too long for type character varying(150)  Call getNextException to see other errors in the batch.], SQL: insert into videos (uploader_id, duration, is_short, thumbnail, title, uploaded, views, id) values (?, ?, ?, ?, ?, ?, ?, ?)
Oct 29, 2022 11:03:02 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
WARN: SQL Error: 0, SQLState: 22001
Oct 29, 2022 11:03:02 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
ERROR: Batch entry 0 insert into videos (uploader_id, duration, is_short, thumbnail, title, uploaded, views, id) values ('UC_ViSsVg_3JUDyLS3E2Un5g', 2060, 'FALSE', 'https://i.ytimg.com/vi/0k28PAgFpGA/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGEgYShhMA8=&rs=AOn4CLDMg7ubsKkmB2-p2PJwXPrrtxJuuQ', 'ATM7 Skyblock Ep42 FTB Industrial Contraptions', 1667041202000, 60, '0k28PAgFpGA') was aborted: ERROR: value too long for type character varying(150)  Call getNextException to see other errors in the batch.
Oct 29, 2022 11:03:02 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
ERROR: ERROR: value too long for type character varying(150)
org.hibernate.exception.DataException: could not execute batch
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:101)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:133)
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:108)
	at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:153)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:193)
	at org.hibernate.internal.StatelessSessionImpl.managedFlush(StatelessSessionImpl.java:467)
	at org.hibernate.internal.StatelessSessionImpl.flushBeforeTransactionCompletion(StatelessSessionImpl.java:701)
	at org.hibernate.internal.StatelessSessionImpl.beforeTransactionCompletion(StatelessSessionImpl.java:671)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
	at me.kavin.piped.utils.ResponseHelper.handleNewVideo(ResponseHelper.java:1621)
	at me.kavin.piped.utils.ResponseHelper.handleNewVideo(ResponseHelper.java:1595)
	at me.kavin.piped.ServerLauncher.lambda$mainServlet$5(ServerLauncher.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into videos (uploader_id, duration, is_short, thumbnail, title, uploaded, views, id) values ('UC_ViSsVg_3JUDyLS3E2Un5g', 2060, 'FALSE', 'https://i.ytimg.com/vi/0k28PAgFpGA/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGEgYShhMA8=&rs=AOn4CLDMg7ubsKkmB2-p2PJwXPrrtxJuuQ', 'ATM7 Skyblock Ep42 FTB Industrial Contraptions', 1667041202000, 60, '0k28PAgFpGA') was aborted: ERROR: value too long for type character varying(150)  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:123)

	... 18 more
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(150)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)

	... 25 more`

### Browser, and OS with Version.

n/a

**Comment by FireMasterK** [comment]
Open a database connection and run this:
```
ALTER TABLE videos ALTER COLUMN thumbnail TYPE varchar(400);
```
You can open a psql client with this command:
```
docker exec -u postgres -it postgres psql -U piped
```
