### ISSUE TITLE
duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by mohammadrafigh** [TeamPiped/Piped#1796]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I constantly receive `duplicate key value violates unique constraint` and `SocketTimeoutException` errors in logs with 100% CPU usage every few seconds.

### To Reproduce

I just run the official docker image behind an nginx proxy.

### Expected behavior

There shouldn't be 100% CPU usage and the error logs should be gone.

### Logs/Errors

```
piped-backend   | Nov 21, 2022 5:20:45 PM com.github.benmanes.caffeine.cache.LocalAsyncCache lambda$handleCompletion$7
piped-backend   | WARNING: Exception thrown during asynchronous load
piped-backend   | java.util.concurrent.CompletionException: java.net.SocketTimeoutException: timeout
piped-backend   | 	at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncLoad$0(CacheLoader.java:109)
piped-backend   | 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
piped-backend   | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
piped-backend   | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
piped-backend   | 	at java.base/java.lang.Thread.run(Unknown Source)
piped-backend   | Caused by: java.net.SocketTimeoutException: timeout
piped-backend   | 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
piped-backend   | 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
piped-backend   | 	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
piped-backend   | 	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
piped-backend   | 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
piped-backend   | 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
piped-backend   | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
piped-backend   | 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
piped-backend   | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
piped-backend   | 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
piped-backend   | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
piped-backend   | 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
piped-backend   | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
piped-backend   | 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
piped-backend   | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
piped-backend   | 	at okhttp3.brotli.BrotliInterceptor.intercept(BrotliInterceptor.kt:40)
piped-backend   | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
piped-backend   | 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
piped-backend   | 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
piped-backend   | 	at me.kavin.piped.utils.DownloaderImpl.executeRequest(DownloaderImpl.java:66)
piped-backend   | 	at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncLoad$0(CacheLoader.java:105)
piped-backend   | 	... 4 more
piped-backend   | 

```

```
piped-backend   | Nov 22, 2022 5:14:04 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
piped-backend   | ERROR: Batch entry 0 insert into channels (uploader, uploader_avatar, verified, uploader_id) values ('Tinie', 'https://yt3.ggpht.com/Oj1vaVmgelFG63clhwxx_fw2ft3N8KL5dff61l4Gov1VZ-U-ek1BYli6KKVSZaX9n1HJJ4lvcg=s48-c-k-c0x00ffffff-no-rj', 'TRUE', 'UCDSX4RQN7fzIlZ1nSubwCcQ') was aborted: ERROR: duplicate key value violates unique constraint "channels_pkey"
piped-backend   |   Detail: Key (uploader_id)=(UCDSX4RQN7fzIlZ1nSubwCcQ) already exists.  Call getNextException to see other errors in the batch.
piped-backend   | Nov 22, 2022 5:14:04 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
piped-backend   | ERROR: ERROR: duplicate key value violates unique constraint "channels_pkey"
piped-backend   |   Detail: Key (uploader_id)=(UCDSX4RQN7fzIlZ1nSubwCcQ) already exists.
piped-backend   | org.hibernate.exception.ConstraintViolationException: could not execute batch
piped-backend   | 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:95)
piped-backend   | 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
piped-backend   | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
piped-backend   | 	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:133)
piped-backend   | 	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:108)
piped-backend   | 	at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:153)
piped-backend   | 	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:193)
piped-backend   | 	at org.hibernate.internal.StatelessSessionImpl.managedFlush(StatelessSessionImpl.java:467)
piped-backend   | 	at org.hibernate.internal.StatelessSessionImpl.flushBeforeTransactionCompletion(StatelessSessionImpl.java:701)
piped-backend   | 	at org.hibernate.internal.StatelessSessionImpl.beforeTransactionCompletion(StatelessSessionImpl.java:671)
piped-backend   | 	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
piped-backend   | 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
piped-backend   | 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
piped-backend   | 	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
piped-backend   | 	at me.kavin.piped.utils.DatabaseHelper.saveChannel(DatabaseHelper.java:197)
piped-backend   | 	at me.kavin.piped.server.handlers.auth.AuthPlaylistHandlers.lambda$importPlaylistResponse$7(AuthPlaylistHandlers.java:340)
piped-backend   | 	at java.base/java.util.Optional.orElseGet(Unknown Source)
piped-backend   | 	at me.kavin.piped.server.handlers.auth.AuthPlaylistHandlers.lambda$importPlaylistResponse$8(AuthPlaylistHandlers.java:340)
piped-backend   | 	at java.base/java.lang.Iterable.forEach(Unknown Source)
piped-backend   | 	at me.kavin.piped.server.handlers.auth.AuthPlaylistHandlers.importPlaylistResponse(AuthPlaylistHandlers.java:338)
piped-backend   | 	at me.kavin.piped.server.ServerLauncher.lambda$mainServlet$35(ServerLauncher.java:318)
piped-backend   | 	at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)
piped-backend   | 	at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250)
piped-backend   | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
piped-backend   | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
piped-backend   | 	at java.base/java.lang.Thread.run(Unknown Source)
piped-backend   | Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into channels (uploader, uploader_avatar, verified, uploader_id) values ('Tinie', 'https://yt3.ggpht.com/Oj1vaVmgelFG63clhwxx_fw2ft3N8KL5dff61l4Gov1VZ-U-ek1BYli6KKVSZaX9n1HJJ4lvcg=s48-c-k-c0x00ffffff-no-rj', 'TRUE', 'UCDSX4RQN7fzIlZ1nSubwCcQ') was aborted: ERROR: duplicate key value violates unique constraint "channels_pkey"
piped-backend   |   Detail: Key (uploader_id)=(UCDSX4RQN7fzIlZ1nSubwCcQ) already exists.  Call getNextException to see other errors in the batch.
piped-backend   | 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
piped-backend   | 	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
piped-backend   | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
piped-backend   | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
piped-backend   | 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
piped-backend   | 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
piped-backend   | 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
piped-backend   | 	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
piped-backend   | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
piped-backend   | 	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:123)
piped-backend   | 	... 22 more
piped-backend   | Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "channels_pkey"
piped-backend   |   Detail: Key (uploader_id)=(UCDSX4RQN7fzIlZ1nSubwCcQ) already exists.
piped-backend   | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
piped-backend   | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
piped-backend   | 	... 29 more
piped-backend   | Nov 22, 2022 5:14:04 AM org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl release
piped-backend   | INFO: HHH000010: On release of batch it still contained JDBC statements
piped-backend   | Nov 22, 2022 5:14:04 AM org.hibernate.engine.jdbc.batch.internal.BatchingBatch performExecution
piped-backend   | ERROR: HHH000315: Exception executing batch [java.sql.BatchUpdateException: Batch entry 0 insert into channels (uploader, uploader_avatar, verified, uploader_id) values ('DJ Fresh', 'https://yt3.ggpht.com/sWFBwBJuy4xwyuJUrfTheXAn8q5y6w92GUTNdHKQt67i_BJ64cLhEwvPLbIsRE6L7z0NJi8Bnw=s48-c-k-c0x00ffffff-no-rj', 'TRUE', 'UC0y8P5OjTKLTpnDt62WJzCA') was aborted: ERROR: duplicate key value violates unique constraint "channels_pkey"
...
```

**Comment by mohammadrafigh** [comment]
No one can help with this?!

**Comment by FireMasterK** [comment]
This error can be safely ignored.

**Comment by mohammadrafigh** [comment]
@FireMasterK then what's the problem with 100% cpu usage?! I face this problem every 10mins or so...

**Comment by FireMasterK** [comment]
1. Stop tagging me
2. I haven't faced this issue, you should attach a profiler and record CPU times, it would help with finding the cause

**Comment by mohammadrafigh** [comment]
1. I know it's an open source project, But If you can't answer to the issues and there is no one responsible then you can close your issue tracker!
2. The problem is with Piped java backend process.
3. If it's all that I can have with this project then I think it's better to remove Piped and use another solution!

**Comment by mohammadrafigh** [comment]
Just for the record if someone reached here. My problem fixed by allocating some amount of swap memory. It seems there was a low memory problem on my instance which causes some process fail to work properly.
