### ISSUE TITLE
PIped.adminforge.de isn't working.

### ISSUE THREAD

**Issue by ligmaballz420** [TeamPiped/Piped#2089]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

You can not see videos on piped.adminforge.de on any page

### To Reproduce

If you open a page on piped.adminforge.de you can not see videos

### Expected behavior

I expected it just to show videos

### Logs/Errors

the console said 
Unchecked runtime.lastError: The message port closed before a response was received.
:1 Unchecked runtime.lastError: The message port closed before a response was received.
:1 Unchecked runtime.lastError: The message port closed before a response was received.
:1 Unchecked runtime.lastError: The message port closed before a response was received.
pipedapi.adminforge.de/config:1          Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
index-a6f52da9.js:791          Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (index-a6f52da9.js:791:26470)
    at Proxy.fetchConfig (index-a6f52da9.js:765:38935)
    at Proxy.mounted (index-a6f52da9.js:765:38886)
    at index-a6f52da9.js:1:25266
    at hn (index-a6f52da9.js:1:14471)
    at kt (index-a6f52da9.js:1:14550)
    at t.__weh.t.__weh (index-a6f52da9.js:1:25146)
    at Of (index-a6f52da9.js:1:15843)
    at Y (index-a6f52da9.js:1:45787)
    at mount (index-a6f52da9.js:1:36088)
pipedapi.adminforge.de/trending?region=US:1          Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
index-a6f52da9.js:791          Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (index-a6f52da9.js:791:26470)
    at Proxy.fetchTrending (TrendingPage-ce6174d8.js:1:751)
    at Proxy.mounted (TrendingPage-ce6174d8.js:1:358)
    at index-a6f52da9.js:1:25266
    at hn (index-a6f52da9.js:1:14471)
    at kt (index-a6f52da9.js:1:14550)
    at t.__weh.t.__weh (index-a6f52da9.js:1:25146)
    at Of (index-a6f52da9.js:1:15843)
    at Af (index-a6f52da9.js:1:16150)
pipedapi.adminforge.de/feed?authToken=1038d2ab-6d19-4e41-bd4e-b6015527333d:1          Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
index-a6f52da9.js:791          Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (index-a6f52da9.js:791:26470)
    at Proxy.fetchFeed (FeedPage-0a981c3b.js:1:1183)
    at Proxy.mounted (FeedPage-0a981c3b.js:1:639)
    at index-a6f52da9.js:1:25266
    at hn (index-a6f52da9.js:1:14471)
    at kt (index-a6f52da9.js:1:14550)
    at t.__weh.t.__weh (index-a6f52da9.js:1:25146)
    at Of (index-a6f52da9.js:1:15843)
    at Af (index-a6f52da9.js:1:16150)
pipedapi.adminforge.de/user/playlists:1          Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
index-a6f52da9.js:791          Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (index-a6f52da9.js:791:26470)
    at Proxy.fetchPlaylists (PlaylistsPage-64c24c38.js:1:365)
    at Proxy.mounted (PlaylistsPage-64c24c38.js:1:220)
    at index-a6f52da9.js:1:25266
    at hn (index-a6f52da9.js:1:14471)
    at kt (index-a6f52da9.js:1:14550)
    at t.__weh.t.__weh (index-a6f52da9.js:1:25146)
    at Of (index-a6f52da9.js:1:15843)
    at Af (index-a6f52da9.js:1:16150)

### Additional context

IT also is not on the instance list anymore

**Comment by ligmaballz420** [comment]
aaanddd its back i feel retarded

**Comment by ligmaballz420** [comment]
andd its down again

**Comment by Bnyro** [comment]
All there services are down, that's not related to Piped in specific.
