### ISSUE TITLE
Can't play any video

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#218]
```
A JSONObject text must begin with '{' at 1 [character 2 line 1]

error: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
	at org.json.JSONObject.<init>(JSONObject.java:222)
	at org.json.JSONObject.<init>(JSONObject.java:406)
	at me.kavin.piped.utils.ResponseHelper.getLBRYStreamURL(ResponseHelper.java:432)
	at me.kavin.piped.utils.ResponseHelper.lambda$streamsResponse$2(ResponseHelper.java:75)
	at me.kavin.piped.utils.ResponseHelper$$Lambda$530/0x0000000000000000.get(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by FireMasterK** [comment]
I can't seem to replicate this issue on the NL instance too, is it still present?

**Comment by B0pol** [comment]
No I can't reproduce

**Comment by FireMasterK** [comment]
It must've been an issue on LBRY's servers.


Either ways, I'll make it so this doesn't affect functionality in the future.
