### ISSUE TITLE
Initial player response is not valid

### ISSUE THREAD

**Issue by notBradPitt** [TeamPiped/Piped#2495]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Getting the following error when trying to watch a certain video. Other videos seems to work fine
![image](https://github.com/TeamPiped/Piped/assets/85218180/1d468d69-c85b-4093-8ed1-85a050ab929a)

### To Reproduce

I've tried watching this video on multiple instances and it gives the same error https://piped.video/watch?v=otDOHt_Jges

### Expected behavior

The video to load

### Logs/Errors

```org.schabi.newpipe.extractor.exceptions.ExtractionException: Initial player response is not valid
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:872)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:78)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at me.kavin.piped.server.handlers.StreamHandlers.lambda$streamsResponse$0(StreamHandlers.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)```

### Browser, and OS with Version.

_No response_

### Additional context

_No response_

**Comment by Bnyro** [comment]
See #2487

**Comment by notBradPitt** [comment]
Thanks for redirecting, had searched for the error and didn't get any result. Seems like I was late to file the issue

**Comment by cyberhardt** [comment]
also getting it on certain instances. this time on il.ax

**Comment by cyberhardt** [comment]
error still persists on il.ax despite not happening on any other instances I tried.

**Comment by techgamers2** [comment]
still happening
