### ISSUE TITLE
Backend: "DSN is required" when SENTRY_DSN set to empty string

### ISSUE THREAD

**Issue by DarkCat09** [TeamPiped/Piped#2587]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I'm trying to run Piped backend without Docker.  
I'm using OpenJDK 17 on Alpine Linux, `./gradlew shadowJar` executes without errors.  
But piped.jar does not start, Sentry throws `IllegalArgumentException` even if I uncomment `SENTRY_DSN` in config.properties and/or set it to empty string.  
I've checked that config is successfully read by Constants.class including SENTRY_DSN option.

### To Reproduce

1. `git clone https://github.com/TeamPiped/Piped-Backend src && cd src`
2. `./gradlew shadowJar`
3. `cp build/libs/piped-1.0-all.jar ../piped.jar && cp config.properties .. && cd ..`
4. `java -jar ./piped.jar`

### Expected behavior

Piped server should start without errors.

### Logs/Errors

```
Exception in thread "main" java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.
	at io.sentry.Sentry.initConfigurations(Sentry.java:291)
	at io.sentry.Sentry.init(Sentry.java:210)
	at io.sentry.Sentry.init(Sentry.java:170)
	at io.sentry.Sentry.init(Sentry.java:156)
	at me.kavin.piped.Main.main(Main.java:38)
```

### Browser, and OS with Version.

Alpine Linux Virtual v3.18

**Comment by DarkCat09** [comment]
Okay, after modifying `Main.java` (I've replaced `Constants.SENTRY_DSN` with `""`) and installing package `gcompat`, it starts with another error, afaik related to Alpine's musl libraries:
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class me.kavin.piped.consts.Constants
	at me.kavin.piped.Main.main(Main.java:61)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/libreqwest9381916879556712187.so: Error relocating /tmp/libreqwest9381916879556712187.so: gnu_get_libc_version: symbol not found [in thread "main"]
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at rocks.kavin.reqwest4j.ReqwestUtils.<clinit>(ReqwestUtils.java:34)
	at me.kavin.piped.utils.RequestUtils.sendGet(RequestUtils.java:23)
	at me.kavin.piped.consts.Constants.<clinit>(Constants.java:202)
	at me.kavin.piped.Main.lambda$main$0(Main.java:40)
	at io.sentry.Sentry.applyOptionsConfiguration(Sentry.java:176)
	at io.sentry.Sentry.init(Sentry.java:169)
	at io.sentry.Sentry.init(Sentry.java:156)
	at me.kavin.piped.Main.main(Main.java:38)
ThrottlingCache: 0 entries
```

**Comment by DarkCat09** [comment]
Can I build libreqwest by myself, or maybe completely disable Sentry that loads this library?

**Comment by DarkCat09** [comment]
Oh, I got it, libreqwest is loaded by Piped, not Sentry. So I need to modify and compile `rocks.kavin.reqwest4j.ReqwestUtils`, then use my version of the library in Piped build.

**Comment by FireMasterK** [comment]
You can build `libreqwest` from https://github.com/TeamPiped/reqwest4j, maybe you could build it as a git dependency.

**Comment by DarkCat09** [comment]
@FireMasterK, thank you for the answer.  
I've cloned the repository, built the rust library in `reqwest-jni` subdirectory, and run `./gradlew shadowJar` (also tried `build`, `jar` tasks). There is no native libraries in the output JAR, only Java code.  
Piped doesn't start with my JAR.  
How to build it?

**Comment by DarkCat09** [comment]
I built reqwest-jni with `cargo build --target x86_64-unknown-linux-musl --release` and added the output .so library to `reqwest4j-1.0.4-all.jar/META-INF/natives/linux/x86_64/libreqwest.so` using 7z archiver.  
Then compiled Piped with custom libreqwest4j JAR, and... it works!

**Comment by DarkCat09** [comment]
https://github.com/DarkCat09/Piped-Alpine  
https://git.dc09.ru/DarkCat09/Piped-Alpine
