### ISSUE TITLE
I can't import playlist directly from youtube.com

### ISSUE THREAD

**Issue by the4anoni** [TeamPiped/Piped#2866]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

https://www.youtube.com/playlist?list=PL6T-wOsBCQccPn2QSjgUSU8lKvbBv0NCN

I can't import this playlist.

### To Reproduce

1. Open playlist in piped
2. Click on import playlist.

### Expected behavior

Playlist should be imported just fine.

### Logs/Errors

org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This channel is not available."
at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.defaultAlertsCheck(YoutubeParsingHelper.java:1587)
at org.schabi.newpipe.extractor.services.youtube.YoutubeChannelHelper.getChannelResponse(YoutubeChannelHelper.java:184)
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.onFetchPage(YoutubeChannelExtractor.java:91)
at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:51)
at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:45)
at me.kavin.piped.utils.DatabaseHelper.saveChannel(DatabaseHelper.java:188)
at me.kavin.piped.server.handlers.auth.AuthPlaylistHandlers.lambda$importPlaylistResponse$8(AuthPlaylistHandlers.java:436)
at java.base/java.util.Optional.orElseGet(Optional.java:364)
at me.kavin.piped.server.handlers.auth.AuthPlaylistHandlers.lambda$importPlaylistResponse$9(AuthPlaylistHandlers.java:436)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at me.kavin.piped.server.handlers.auth.AuthPlaylistHandlers.importPlaylistResponse(AuthPlaylistHandlers.java:434)
at me.kavin.piped.server.ServerLauncher.lambda$mainServlet$42(ServerLauncher.java:406)
at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)
at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:249)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)

### Browser, and OS with Version.

Vivaldi on Windows and Debian.

**Comment by hakrishi** [comment]
I'm having troubles importing using a CSV from Google Takeout. Are you importing from a link? If so, how can this be achieved?
Note I am using the official instance, piped.video

**Comment by the4anoni** [comment]
> troubles importing using a CSV from Google Takeout

Last time I did this It worked fine.



> Are you importing from a link?

Yes



> I'm having troubles importing using a CSV from Google Takeout. Are you importing from a link? If so, how can this be achieved? Note I am using the official instance, piped.video

If that's your playlist make sure it's public/at least people with link have access. Copy link to it and paste it to piped.
