### ISSUE TITLE
vue-loader-v16@npm:16.1.2 - Registry failed to return reference "16.1.2"

### ISSUE THREAD

**Issue by debpalash** [TeamPiped/Piped#296]
```
i [Error]: vue-loader-v16@npm:16.1.2: Registry failed to return reference "16.1.2"
    at Object.resolve (C:\Users\pc\.yarn\releases\yarn-berry.cjs:2:232471)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async n.resolve (C:\Users\pc\.yarn\releases\yarn-berry.cjs:2:337541)
    at async n.resolve (C:\Users\pc\.yarn\releases\yarn-berry.cjs:2:337541)
    at async C:\Users\pc\.yarn\releases\yarn-berry.cjs:2:357868
    at async Module.w (C:\Users\pc\.yarn\releases\yarn-berry.cjs:2:418487)
    at async d (C:\Users\pc\.yarn\releases\yarn-berry.cjs:2:357831)
    at async Promise.all (index 48) {
  reportExtra: undefined,
  reportCode: 16
}
```
issue on yarnpkg/berry [https://github.com/yarnpkg/berry/issues/2012#issuecomment-783593285](url)

**Comment by FireMasterK** [comment]
By any chance, are you using npm? You should be using yarn.

**Comment by debpalash** [comment]
> By any chance, are you using npm? You should be using yarn.

that's after running `yarn install`

**Comment by debpalash** [comment]
Thanks. Good project work
