### ISSUE TITLE
HLS streams no longer work after qhash addition

### ISSUE THREAD

**Issue by hauntii** [TeamPiped/Piped#3162]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

HLS streams have stopped working after the addition of the proxy qhash, as while the HLS url itself has the `qhash` param, the manifest response doesn't give back URLs with the `qhash` param added, causing a 500 error (`No qhash provided`).

### To Reproduce

1. Open inspect console on network tab to ensure network is logging
2. Open [this url](https://piped.video/watch?v=jfKfPfyJRdk), a livestream
3. Observe as the API returns 500 errors due to the missing `qhash` params

### Expected behavior

HLS manifest should return urls with the `qhash` param so that HLS streams can be played.

### Logs/Errors

```
{
    "severity": 2,
    "category": 1,
    "code": 1001,
    "data": [
        "https://pipedproxy-yyz.kavin.rocks/api/manifest/hls_playlist/expire/1700547800/ei/ePhbZbHIGcLP1AHEuvXBAQ/ip/37.19.211.70/id/jfKfPfyJRdk.2/itag/270/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgovp/gir%3Dyes%3Bitag%3D137/rqh/1/hls_chunk_host/rr5---sn-tt1e7nls.googlevideo.com/playlist_duration/3600/manifest_duration/3600/vprv/1/playlist_type/DVR/initcwndbps/4055000/mh/rr/mip/37.19.211.85/mm/44/mn/sn-tt1e7nls/ms/lva/mv/m/mvi/5/pl/24/dover/13/pacing/0/short_key/1/keepalive/yes/fexp/24007246/mt/1700527947/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgovp,rqh,playlist_duration,manifest_duration,vprv,playlist_type/sig/ANLwegAwRgIhAKBZk2BrRJa2FN0fyX8Wf0XAZ22ZLiv0KwPp1E8uOcT5AiEAjIHSYA2BH2yOLLiFy91plEwVAdtlBcqLnkj7xMWLicA%3D/lsparams/hls_chunk_host,initcwndbps,mh,mip,mm,mn,ms,mv,mvi,pl/lsig/AM8Gb2swRAIgaAv5wLh_l31i2k6LbgR65Cj6LFtDPxmKuM022PTlbjkCIAkG8Chx0qjI2oFvdeLbxX-OH4Rn-k1rWHF-Si4Cgu0J/playlist/index.m3u8?host=manifest.googlevideo.com",
        500,
        "No qhash provided",
        {
            "cache-control": "private",
            "content-length": "17",
            "content-type": "text/plain; charset=utf-8"
        },
        0
    ],
    "handled": false,
    "message": "Shaka Error 1001",
    "stack": "Error: Shaka Error 1001\n    at new I (https://piped.video/assets/shaka-player.ui-jLgbSuTI.js:1:24198)\n    at Qm (https://piped.video/assets/shaka-player.ui-jLgbSuTI.js:1:424103)\n    at G1.h (https://piped.video/assets/shaka-player.ui-jLgbSuTI.js:1:425528)\n    at Yr (https://piped.video/assets/shaka-player.ui-jLgbSuTI.js:1:4174)\n    at z1.next (https://piped.video/assets/shaka-player.ui-jLgbSuTI.js:1:4472)\n    at t (https://piped.video/assets/shaka-player.ui-jLgbSuTI.js:1:4701)"
}
```

### Browser, and OS with Version.

All, but tested on
Chrome for macOS 119.0.6045.159 on macOS 14.1 Sonoma
AVPlayer, iOS 14.1

**Comment by hauntii** [comment]
This may have been a better fit for [piped-proxy](https://github.com/TeamPiped/piped-proxy), but I was unsure as it was also a part of the backend...

If anyone has any issue with this being here instead of there I'd be happy to close this and move to an issue there.
