### ISSUE TITLE
Videos not loading at all on all instances

### ISSUE THREAD

**Issue by HarveyVonG** [TeamPiped/Piped#3213]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Libretube app won't play or load videos since I updated the app to its latest version. 
Using version 0.20.1

### To Reproduce

Open app.
Click on video.
Video either:
Buffers, and doesn't load at all.
Crashes the app.
Repeat.

### Expected behavior

Video should load and play as usual.

### Logs/Errors

kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:158)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e70782b, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at okio.-SegmentedByteString.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:1)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:2)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:102)
	... 9 more
    

### Browser, and OS with Version.

Android 13

### Additional context

Ive uninstalled and reinstalled twice, nothing works.

**Comment by Pamilg8** [comment]
My problem continues on issue #3196.Some people's app is experiencing an error. Please enter information such as android version.bu I don't think there is a solution in this case. YouTube proxy doesn't work because of youtube restrictions😔

**Comment by Bnyro** [comment]
LibreTube doesn't support outdated instances.

**Comment by tomastan** [comment]
> LibreTube doesn't support outdated instances.

I'm facing same issues. None of instances from the list work. Including kavin.rocks (official).

How to find and setup up to date instances?

![Screenshot_2023-12-05-14-32-34-671_com github libretube](https://github.com/TeamPiped/Piped/assets/68420660/92c3a5d0-175f-405d-9ee1-d5c7a4b70758)
