### ISSUE TITLE
cant watch videos

### ISSUE THREAD

**Issue by sheeshman3** [TeamPiped/Piped#3434]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Everytime i click on a video, i get this message "Could not fetch embedded watch page" with a long script

### To Reproduce

Open piped.video
click on any video
problem happens

### Expected behavior

The video playing

### Logs/Errors

org.schabi.newpipe.extractor.exceptions.ParsingException: Could not fetch embedded watch page
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptUrlWithEmbedWatchPage(YoutubeJavaScriptExtractor.java:114)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptPlayerCode(YoutubeJavaScriptExtractor.java:65)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptPlayerManager.extractJavaScriptCodeIfNeeded(YoutubeJavaScriptPlayerManager.java:344)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptPlayerManager.getSignatureTimestamp(YoutubeJavaScriptPlayerManager.java:93)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:837)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:67)
	at me.kavin.piped.server.handlers.StreamHandlers.lambda$streamsResponse$0(StreamHandlers.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.Exception: error sending request for url (https://www.youtube.com/embed/hhmvZwQ9bJU): error trying to connect: unsuccessful tunnel
	at me.kavin.piped.utils.DownloaderImpl.execute(DownloaderImpl.java:117)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:77)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:46)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptUrlWithEmbedWatchPage(YoutubeJavaScriptExtractor.java:111)
	... 11 more
Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: error sending request for url (https://www.youtube.com/embed/hhmvZwQ9bJU): error trying to connect: unsuccessful tunnel
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at me.kavin.piped.utils.DownloaderImpl.execute(DownloaderImpl.java:115)
	... 14 more
Caused by: java.lang.Exception: error sending request for url (https://www.youtube.com/embed/hhmvZwQ9bJU): error trying to connect: unsuccessful tunnel

### Browser, and OS with Version.

Librewolf, Windows 10

**Comment by Pamilg8** [comment]
Because the servers are not listed. It will be fixed when they come back

**Comment by sheeshman3** [comment]
what do you mean choose from the available ones?

**Comment by Fantom1214B** [comment]
Same problem and on top of that the api call doesn't work either

![image](https://github.com/TeamPiped/Piped/assets/158606033/17d065a1-d2e8-4e70-8ab0-174f6d99000e)

**Comment by Pamilg8** [comment]
![Screenshot_20240303-115513_Chrome](https://github.com/TeamPiped/Piped/assets/149590337/b9426a23-3679-4f39-ab67-01c037542d98)
Because the servers you are using are not available. Try an existing one from the settings.

**Comment by sheeshman3** [comment]
do i have to create a new acc for each instance?

**Comment by sheeshman3** [comment]
Thanks, that fixed it
