### ISSUE TITLE
Trying to self host but getting this issue: Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by Provider2436** [TeamPiped/Piped#3521]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I'm trying to self host my own instance of piped and this is my docker-compose file: 
```yml
version: "3.8"
services:
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        ports:
            - "8585:8080"
        volumes:
            - /data/piped/config.properties:/app/config.properties
        depends_on:
            - postgres
            - ytproxy
    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        volumes:
            - /data/piped/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=password
    ytproxy:
        image: 1337kavin/ytproxy:latest
        restart: unless-stopped
        volumes:
          - "/docker/yotter/ytproxy:/app/socket"
 ```
I don't know what I'm doing wrong, I don't have watchtower here because it's deployed on it's own and I use nginx proxy manager.

### To Reproduce

1. docker-compose up -d
2. see the logs

### Expected behavior

Have piped deployed and usable.

### Logs/Errors

These are the complete error logs that I'm getting for the piped container:
```
Exception in thread "main" java.lang.ExceptionInInitializerError

	at me.kavin.piped.Main.main(Main.java:45)

Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: config.properties (Is a directory)

	at me.kavin.piped.consts.Constants.<clinit>(Constants.java:206)

	... 1 more

Caused by: java.io.FileNotFoundException: config.properties (Is a directory)

	at java.base/java.io.FileInputStream.open0(Native Method)

	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)

	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)

	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)

	at java.base/java.io.FileReader.<init>(FileReader.java:60)

	at me.kavin.piped.consts.Constants.<clinit>(Constants.java:123)

	... 1 more
```

### Browser, and OS with Version.

Librewolf 124 and fedora 39 both client and server side

**Comment by Bnyro** [comment]
Please ask such questions via our Matrix room.

`/data/piped/config.properties` has to be an already existing file (https://github.com/TeamPiped/Piped-Docker/blob/main/template/config.properties), also see https://github.com/TeamPiped/Piped-Docker/blob/main/template/docker-compose.nginx.yml#L23.

**Comment by Bnyro** [comment]
It's not recommended or supported to build your own docker compose template, that's why there are already prebuilt once...
