### ISSUE TITLE
DeArrow doesn't work

### ISSUE THREAD

**Issue by Insprill** [TeamPiped/Piped#3523]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

DeArrow no longer appears to be functioning.

### To Reproduce

1. Enable DeArrow support.
2. Look at any popular channel (e.g. [Linus Tech Tips](https://piped.video/channel/UCXuqSBlHAE6Xw-yeJA0Tunw)).
3. Observe none of the videos having DeArrow thumbnails/titles.

### Expected behavior

DeArrow should work.

### Logs/Errors

```
piped-backend   | An error occoured in the path: /dearrow
piped-backend   | java.lang.Exception: All SponsorBlock servers are down
piped-backend   | 	at me.kavin.piped.utils.SponsorBlockUtils.lambda$fetchDeArrowedCf$9(SponsorBlockUtils.java:129)
piped-backend   | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
piped-backend   | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
piped-backend   | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
piped-backend   | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
```

### Browser, and OS with Version.

Firefox Develop Editions v125.0b6
Arch Linux

Firefox v124.0.1
Windows 11

### Additional context

SponsorBlock is still working as expected.

**Comment by Insprill** [comment]
I haven't seen this issue in months, so I'm assuming it got fixed at some point.
