### ISSUE TITLE
Got error: "Sign in to confirm that you're not a bot"

### ISSUE THREAD

**Issue by DuplicantWood** [TeamPiped/Piped#3658]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

On my private instance and with some others i have tested in the public list i am seeing "Got error: "Sign in to confirm that you're not a bot"" instead of a video

Here is a link from a public instance with the same problem: 

https://piped.r4fo.com/watch?v=2G-L0u_L0qU

### To Reproduce

Open this url on this instance 

https://piped.r4fo.com/watch?v=2G-L0u_L0qU

See error

### Expected behavior

Video to play normally

### Browser, and OS with Version.

Happens on multiple browsers and devices

### Additional context

I'm assuming it's related to something google/youtube have done as invidious instances are having similar issues.

https://github.com/iv-org/invidious/issues/4734

**Comment by milutinke** [comment]
Is there any solution for this?

**Comment by 00-kat** [comment]
> Is there any solution for this?

Cobalt [implemented OAuth](https://github.com/imputnet/cobalt/issues/551#issuecomment-2156024956), but other than that there's not been much in terms of solving this issue...

**Comment by Anoerak** [comment]
Restarting all containers fixed it for me tonight.

**Comment by AndrewHoang1995** [comment]
> Restarting all containers fixed it for me tonight.

Really !!!

**Comment by LivingWithHippos** [comment]
> Restarting all containers fixed it for me tonight.

Didn't work for me, you  probably got "B" tested ;D

jokes aside, I have another request that may warrant a separate issue: 
I opened a page to use the share button and copy the original youtube link, but the error message "eats" away all the UI, I think it would be nice if a partial interface could still be shown in this case

**Comment by Tamarindo94** [comment]
This is happening to me on the majority of videos (~8 out of 10) and on different instances, to the point I had to go back to using vanilla youtube.
Sadly, I dont know enough about piped or youtube's inner workings to be able to help, but I hope I can bring more attention to this issue. My fear is that this change could make piped and other frontends unusable sooner than we think if a solution isn't found

**Comment by alimovlex** [comment]
> Is there any solution for this?

Yes. Just obtain youtube API keys and paste the API_SECRET to src/main.js function.
`getAuthToken() {
         return this.getPreferenceString("authToken" + this.hashCode(this.authApiUrl()));
} `        
Everything works.

**Comment by alimovlex** [comment]
> This is happening to me on the majority of videos (~8 out of 10) and on different instances, to the point I had to go back to using vanilla youtube. Sadly, I dont know enough about piped or youtube's inner workings to be able to help, but I hope I can bring more attention to this issue. My fear is that this change could make piped and other frontends unusable sooner than we think if a solution isn't found

You can host your own instance instead and paste the token as I have written above.

**Comment by AndrewHoang1995** [comment]
> You can host your own instance instead and paste the token as I have written above.

If I use Docker, how can I rebuild it? I am looking forward to an update from the team regarding documentation and Docker for this temporary solution

**Comment by clot27** [comment]
This is coming so often on official (piped.video) instance, approximately 7 of 10 videos. I haven't tried to change instance yet, I have switched to invidious.

**Comment by danl76** [comment]
Your modify the main.js like this?

getAuthToken() { return this.getPreferenceString("authToken" + this.hashCode(API_KEY)); },

Where API_KEY = your yt api key

Also how do get into the docker container to modify main.js? I tried bash but that'd didn't work.

**Comment by LivingWithHippos** [comment]
> Your modify the main.js like this?
> 
> getAuthToken() { return this.getPreferenceString("authToken" + this.hashCode(API_KEY)); },
> 
> Where API_KEY = your yt api key
> 
> Also how do get into the docker container to modify main.js? I tried bash but that'd didn't work.
> 

When bash doesn't work try `sh` ;D

Where is the file located BTW?

**Comment by LivingWithHippos** [comment]
Partial docker instructions, untested, try only if you know what these means:

1. open your piped instance
2. right click -> view page source or whatever your browser calls it
3. find out the name of the javascript bundled file, mine is `<script type="module" crossorigin src="/assets/index-WHXXydFZ.js"></script>`

At this point you can either extract it from the container, change it and mount it back (easier, persist across restarts, may break the frontend if the containers are updated) or manually edit it in place (no time so will do this for now, may need restart of the container, may break anyway or just not work) or add the sed command to the start script (it's already doing something similar for the instance name)

5. enter the piped frontend container with its name, I used `docker exec -it "piped-frontend" /bin/sh;`
6. enter the assets folder with `cd /usr/share/nginx/html/assets`
7. swap the authToken with `sed -i 's/"authToken"/"YOUR_TOKEN"/g' index-YOUR_FILE.js`
8. ???
9. If you force refresh the page and check the sources again you can click on the js file and see if it has been changed or not

**Comment by enticedwanderer** [comment]
I've tried to do what above was suggested with the substitution of the authToken with an API key for Youtube Data v3 (plain API key not OAuth) and it just results in completely broken piped frontend. No trace or any message in the console. I have confirmed that it is substituted correctly in the browser with cache disabled (just in case).

What's supposed to happen when you swap out the hardcoded authToken string? Can someone provide clearer instructions on how to do this?

**Comment by Bnyro** [comment]
Everything written above about patching `getAuthToken()` is not true, that authToken is only used to authenticate at Piped instances with your Piped account, it's not related to the visitor tokens used for extracting data from YouTube.

Obtaining YouTube API keys and only setting them in the frontend doesn't solve the problem at all, because the YouTube API key would need to be used at the Piped backend anyways ...

**Comment by Bnyro** [comment]
You probably want to save yourself that time and either get a new IP address that's not blocked from YouTube or put a proxy / VPN in front of your instance.

**Comment by milutinke** [comment]
> You probably want to save yourself that time and either get a new IP address that's not blocked from YouTube or put a proxy / VPN in front of your instance.

Invidious made a IPv6 rotation tool, so that is another way of solving the issue. It needs a bit of setup, but works pretty good on a couple of instances I saw using it.

**Comment by bonswouar** [comment]
> > You probably want to save yourself that time and either get a new IP address that's not blocked from YouTube or put a proxy / VPN in front of your instance.
> 
> Invidious made a IPv6 rotation tool, so that is another way of solving the issue. It needs a bit of setup, but works pretty good on a couple of instances I saw using it.

Unfortunately lots of instances had their whole IPV6 /64 range blocked recently. I guess it depends of the provider

**Comment by Bnyro** [comment]
> Unfortunately lots of instances had their whole IPV6 /64 range blocked recently. I guess it depends of the provider
>
Yes, all my Hetzner IPv6 ranges are blocked too since some days :/

**Comment by milutinke** [comment]
I heard https://stylenhost.com/ still works.

**Comment by bonswouar** [comment]
> Maybe we should compile a list of providers that work and don't work.

Not sure this is a good idea, could make things much easier for Google :sweat_smile:

**Comment by IngwiePhoenix** [comment]
Ran into this issue a while ago and haven't had time to look into it.
For the meantime I guess I will just deploy [gluetun](https://github.com/qdm12/gluetun) to just use a VPN instead. Because my VPS is indeed with Hetzner... Welp, that's unfortunate.
Aside from IPv6 rotation, is there any other idea on how to fix that issue?
Thanks!

**Comment by danl76** [comment]
Being it was the new-pipe extractor that broke, and they just fixed the issue on their side, couldn't we get their updated extractor and plug it in?

**Comment by enticedwanderer** [comment]
Latest piped-backend seems to have incorporated [the change](https://github.com/TeamNewPipe/NewPipeExtractor/pull/1197) already. However, for me it doesn't change anything, even with the latest docker image I get the antibot prompt. Exact same instance from my home IP address works fine without any changes, so IP reputation also plays a role.

**Comment by CelianGdfrd** [comment]
> Ran into this issue a while ago and haven't had time to look into it. For the meantime I guess I will just deploy [gluetun](https://github.com/qdm12/gluetun) to just use a VPN instead. Because my VPS is indeed with Hetzner... Welp, that's unfortunate. Aside from IPv6 rotation, is there any other idea on how to fix that issue? Thanks!

Hi, IPV6 rotation didn't help for me, as my whole IP range seems to be restricted. Can't deploy a new IPV6 to my server, and ran an update without more luck, so I'm just going to try Gluetun aswell.

**Comment by Arcegis** [comment]
I can confirm that pretty much all instances, even brand new deployed ones, receive the message "Sign in to confirm you are not a bot." Besides, YouTube now streams unskippable ads, even with UBlock Origin...

**Comment by s1nistr4** [comment]
This issue is cropping up more and more, Google really is playing whack-a-mole with piped instances, I recommend passing the API through multiple proxies via proxychains and spoofing it to look more like a real user

**Comment by IngwiePhoenix** [comment]
I did get Gluetun to work but now the backand is snails-slow in returning basically any video or thumbnail. Have any of you had better luck? Provider is ProtonVPN. I doubt they would allow traffic through tor, and I honestly am not sure how to make a transparent proxy out of tor to just route the piped-backend through...

However, the JMusicBot Discord bot that I selfhost - from home - does still work with no bans or alike and I doubt their dependency, LavaPlayer, is doing a whole lot different to piped's backend.

Sidenote, why is it poking into a Matrix channel exactly? I noticed that while peeking at the logs. Found it curious.

**Comment by mpeter50** [comment]
> I doubt they would allow traffic through tor, and I honestly am not sure how to make a transparent proxy out of tor to just route the piped-backend through...

Wouldn't that be even slower?

---

Maybe it would be somewhat of a solution to spin up instances running on or proxied to popular public networks, like coffee shops, schools and universities, libraries, whatever. Of course easiest if you work there and you wont get into trouble for it.
Maybe also on residential networks when you know that you can get a new IP address relatively easily (like power cycling the ISP router if you can afford the outages for yourself, or something like that).

Yeah yeah full IPv6 ranges are getting blocked.. of VPS providers. But can they afford this for residential IPv6 ranges? And then the same applies to IPv4 addresses, which might (?) be changeable less often, but which is also even hotter with common usage when you are behind CGNAT.

The point would not be just to try to see if a popular piped instance could run without ban on a network that is basically already accounted for by google as one that generates relatively high traffic.
But also to make this shit tactic of google unfeasible to them, by making it break youtube for a lot of common users, so that they would need to consider stopping to do that.
And then it might also be beneficial that users who directly use youtube.com on that network would be solving the verifications if they want to watch it.

What do you think? Does this sound too silly, or is it flawed?

**Comment by IngwiePhoenix** [comment]
@mpeter50 
> Wouldn't that be even slower?

Set hops to 1 and it wouldn't, actually. More hops, nore rings around the onion(routing). Since this is *just* Youtube, all we care about is masquerading the outgoing IP; kinda like NAT. So with Tor set to 1 hop, it could actually be fine o.o Once a connection ("circuit") is established, it is pretty good.

Also, we keep talking IPv6 ranges; what about IPv4? I am drawing a blank here, but what if you reduced the Docker CNI to single stack IPv4 and thus made the backend only operate on that - thus using the host's outgoing public IPv4 for requests. Is that viable?

But wait, "public network"... Cloudflare. I have an idea - well, a thought. Their WARP service provided through 1.1.1.1 can *also* act as a VPN. I'll see if I can get WARP to work inside Docker and replace that with Gluetun and see what happens after that. Who knows...?

**Comment by mycodedoesnotcompile2** [comment]
@IngwiePhoenix, you are right. The future to counter these IP blacklisting is to use different tunneling networks to offload and to "spread" the traffic. Dividing and ruling.

@codenyte, thanks really interesting.

Anyway, what I can tell so far is that, on a cloud environment where I have currently my Invidious instance blocked with this awful *"Sign to confirm"* crap, I can escape this bug by routing outgoing Invidious traffic to Tor.
Just like [this option](https://git.sr.ht/~heckyel/yt-local#using-tor) on the good `yt-local` tool.

**Comment by Astolfo2001** [comment]
I currently can't access any video via Piped because of the whole "Sign in to confirm that you're not a bot" BS.

**Comment by user-naa** [comment]
I am having this error in ALL instances. Sometimes some instances allow me to watch videos, but after several videos same error. I hope this will not be the end of Piped(((

**Comment by PestoPosta** [comment]
I to am having this issue.

**Comment by mycodedoesnotcompile2** [comment]
> I found this one can run in non-privileged-mode https://github.com/ArcticLampyrid/docker-warp-socks5
> 
> You can add this to the docker-compose file
> 
> ```
>     warp:
>         image: qiqiworld/warp-socks5:latest
>         restart: unless-stopped
>         container_name: warp
> ```
> 
> Also add `REQWEST_PROXY: socks5://warp:40000` to the `config/config.properties` file
> 
> Then you backend will use cloudflare WARP as the outgoing proxy.

Thanks !

But *"REQWEST_PROXY"* or *"REQUEST_PROXY"* ?
This is a standard env variable for setting outgoing proxy ?

**Comment by ngn13** [comment]
recently I've been experiencing this issue a lot, and I wrote a script to find available instances for a given video:
```
[500] https://pipedapi.kavin.rocks: Got error: "Sign in to confirm that you're not a bot"
[200] https://pipedapi.leptons.xyz: success
[500] https://pipedapi.r4fo.com: Got error: "Sign in to confirm that you're not a bot"
[200] https://pipedapi-libre.kavin.rocks: success
[500] https://pipedapi.in.projectsegfau.lt: Got error: "Sign in to confirm that you're not a bot"
[500] https://pipedapi.smnz.de: Got error: "Sign in to confirm that you're not a bot"
[500] https://pipedapi.astartes.nl: Got error: "Sign in to confirm that you're not a bot"
[500] https://pipedapi.drgns.space: Got error: "Sign in to confirm that you're not a bot"
[500] https://piapi.ggtyler.dev: Got error: "Sign in to confirm that you're not a bot"
[500] https://pipedapi.phoenixthrush.com: Got error: "Sign in to confirm that you're not a bot"
[200] https://schaunapi.ehwurscht.at: success
[500] https://pipedapi.darkness.services: Got error: "Sign in to confirm that you're not a bot"
```
so most the instances are currently unavailable due to this issue

also I want to mention that **I don't think this is an IP blacklist issue**, I tried using multiple different IPv6 and IPv4 addresses for my instance, after successfully watching one or two videos, the issue comes back again, I think youtube has a new way to verify actual clients/detect "bots", this is backed up by the fact that [people having this issue while using NewPipe](https://github.com/TeamNewPipe/NewPipe/issues/11139), are not having this issue when they visit the actual youtube website and try to watch the same video

**Comment by esme518** [comment]
``> > I found this one can run in non-privileged-mode https://github.com/ArcticLampyrid/docker-warp-socks5
> > You can add this to the docker-compose file
> > ```
> >     warp:
> >         image: qiqiworld/warp-socks5:latest
> >         restart: unless-stopped
> >         container_name: warp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also add `REQWEST_PROXY: socks5://warp:40000` to the `config/config.properties` file
> > Then you backend will use cloudflare WARP as the outgoing proxy.
> 
> Thanks !
> 
> But _"REQWEST_PROXY"_ or _"REQUEST_PROXY"_ ? This is a standard env variable for setting outgoing proxy ?

Check the https://github.com/TeamPiped/Piped-Backend/blob/master/config.properties at line 12-16
```
# Outgoing proxy to be used by reqwest4j - eg: socks5://127.0.0.1:1080
#REQWEST_PROXY: socks5://127.0.0.1:1080
# Optional proxy username and password
#REQWEST_PROXY_USER: username
#REQWEST_PROXY_PASS: password
```

**Comment by mycodedoesnotcompile2** [comment]
> recently I've been experiencing this issue a lot, and I wrote a script to find available instances for a given video:
> 
> ```
> [500] https://pipedapi.kavin.rocks: Got error: "Sign in to confirm that you're not a bot"
> [200] https://pipedapi.leptons.xyz: success
> [500] https://pipedapi.r4fo.com: Got error: "Sign in to confirm that you're not a bot"
> [200] https://pipedapi-libre.kavin.rocks: success
> [500] https://pipedapi.in.projectsegfau.lt: Got error: "Sign in to confirm that you're not a bot"
> [500] https://pipedapi.smnz.de: Got error: "Sign in to confirm that you're not a bot"
> [500] https://pipedapi.astartes.nl: Got error: "Sign in to confirm that you're not a bot"
> [500] https://pipedapi.drgns.space: Got error: "Sign in to confirm that you're not a bot"
> [500] https://piapi.ggtyler.dev: Got error: "Sign in to confirm that you're not a bot"
> [500] https://pipedapi.phoenixthrush.com: Got error: "Sign in to confirm that you're not a bot"
> [200] https://schaunapi.ehwurscht.at: success
> [500] https://pipedapi.darkness.services: Got error: "Sign in to confirm that you're not a bot"
> ```
> 
> so most the instances are currently unavailable due to this issue
> 
> also I want to mention that **I don't think this is an IP blacklist issue**, I tried using multiple different IPv6 and IPv4 addresses for my instance, after successfully watching one or two videos, the issue comes back again, I think youtube has a new way to verify actual clients/detect "bots", this is backed up by the fact that [people having this issue while using NewPipe](https://github.com/TeamNewPipe/NewPipe/issues/11139), are not having this issue when they visit the actual youtube website and try to watch the same video

Thanks, very interesting !

Also: https://farside.link/ + https://github.com/benbusby/farside/

**Comment by Pamilg9** [comment]
The Invisious team has found a solution: https://github.com/iv-org/youtube-trusted-session-generator

**Comment by I-I-IT** [comment]
Surprised to not have seen this proposed : various apps (Grayjay being one) fetch the video from the iOS client to solve the issue.

FreeTube fix : 
https://github.com/FreeTubeApp/FreeTube/issues/5502#issuecomment-2261544217

AFAIK, the issue here is more related to Google banning specific method of obtaining videos, not yet full IP ranges. The fix from invidious concerning this is here : https://github.com/iv-org/inv_sig_helper

**Comment by Pamilg9** [comment]
> Bu təklifi görmədiyimə qarşılanıram: müxtəlif proqramlar (Grayjay birdir) problemi həll etmək üçün videonu iOS üzərindən alır. Baxın: https://gitlab.futo.org/videostreaming/plugins/youtube/-/commit/be0e7891727986154f8482574ac02973fdbd4886
> 
> FreeTube düzəlişi: [FreeTubeApp/FreeTube#5502 (şərh)](https://github.com/FreeTubeApp/FreeTube/issues/5502#issuecomment-2261544217)
> 
> AFAIK, burada daha çox Google-un hələ tam IP diapazonu əldə etmək üçün xüsusi metodu olmayan video icazəsi ilə bağlıdır. Bununla bağlı invidious irəli düzəliş burada: https://github.com/iv-org/inv_sig_helper (burada da bu barədə danışılır [https://gitlab.futo.org/videostreaming/plugins/youtube/-/commit/f57b7b330f566ccc4669fd9a627196782d](https://gitlab.futo.org/videostreaming/plugins/youtube/-/commit/f57b7b330f566ccc4669fd9a62719601d8167228) )

These are another problems

**Comment by Pamilg9** [comment]
1. https://github.com/iv-org/invidious/commit/2d18ff1f80aa804a11108f346a7a3a20f4eb191d

2. https://github.com/iv-org/invidious/commit/2d7869b48ba1c1aca04fd66c52d37853321775cf
They have already merged PR. Piped would fix it

**Comment by nikkon226** [comment]
> > recently I've been experiencing this issue a lot, and I wrote a script to find available instances for a given video:
> > ```
> > [500] https://pipedapi.kavin.rocks: Got error: "Sign in to confirm that you're not a bot"
> > [200] https://pipedapi.leptons.xyz: success
> > [500] https://pipedapi.r4fo.com: Got error: "Sign in to confirm that you're not a bot"
> > [200] https://pipedapi-libre.kavin.rocks: success
> > [500] https://pipedapi.in.projectsegfau.lt: Got error: "Sign in to confirm that you're not a bot"
> > [500] https://pipedapi.smnz.de: Got error: "Sign in to confirm that you're not a bot"
> > [500] https://pipedapi.astartes.nl: Got error: "Sign in to confirm that you're not a bot"
> > [500] https://pipedapi.drgns.space: Got error: "Sign in to confirm that you're not a bot"
> > [500] https://piapi.ggtyler.dev: Got error: "Sign in to confirm that you're not a bot"
> > [500] https://pipedapi.phoenixthrush.com: Got error: "Sign in to confirm that you're not a bot"
> > [200] https://schaunapi.ehwurscht.at: success
> > [500] https://pipedapi.darkness.services: Got error: "Sign in to confirm that you're not a bot"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so most the instances are currently unavailable due to this issue
> > also I want to mention that **I don't think this is an IP blacklist issue**, I tried using multiple different IPv6 and IPv4 addresses for my instance, after successfully watching one or two videos, the issue comes back again, I think youtube has a new way to verify actual clients/detect "bots", this is backed up by the fact that [people having this issue while using NewPipe](https://github.com/TeamNewPipe/NewPipe/issues/11139), are not having this issue when they visit the actual youtube website and try to watch the same video
> 
> Thanks, very interesting !
> 
> Could you propose your script to: https://farside.link/ + https://github.com/benbusby/farside/

This is the one that I wrote. Feel free to put in your favorite video handle:

    #!/bin/bash

    for i in $(curl -s 'https://piped-instances.kavin.rocks/' --compressed -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Referer: https://piped.video/' -H 'Origin: https://piped.video'  | jq -r -c '.[] | .api_url'); do
        ret=$(curl "$i/streams/gUVLnK3kOK0" --silent | jq -r -c '.message')
    
        printf "%-50s %s\n" "[$i]:" "$ret"
    done

**Comment by I-I-IT** [comment]
Just pointing out that this is indeed not an IP blacklisting issue. I tried using LibreTube with the Piped proxy disabled (meaning it directly connected to Google servers) on Wi-Fi, and I still got the "Sign-in,..." error.

My best guess would be that YouTube is detecting that requests come from the "Piped API".

**Comment by lbrealdev** [comment]
> I currently can't access any video via Piped because of the whole "Sign in to confirm that you're not a bot" BS.

Yesterday I had the same error, so I changed the instance from **kavin.rocks** to **r4fo.com*** and the videos started working.

**Comment by I-I-IT** [comment]
> @I-I-IT Incorrect. The whole point of LibreTube is that it uses the Piped API. When you disable the proxy _for videos_, the app still uses a Piped instance to attempt to load all the information required to start the videos: [libre-tube/LibreTube#6366 (comment)](https://github.com/libre-tube/LibreTube/issues/6366#issuecomment-2294846881).

Thank you. I see that piped.video (official mirror) is working well. Any way this could be used by third-parties like LibreTube ?

**Comment by Pamilg9** [comment]
> > @I-I-IT Incorrect. The whole point of LibreTube is that it uses the Piped API. When you disable the proxy _for videos_, the app still uses a Piped instance to attempt to load all the information required to start the videos: [libre-tube/LibreTube#6366 (comment)](https://github.com/libre-tube/LibreTube/issues/6366#issuecomment-2294846881).
> 
> Thank you. I see that piped.video (official mirror) is working well. Any way this could be used by third-parties like LibreTube ?

It doesn't work for everyone (me). You just have to wait for the fix

**Comment by SpidFightFR** [comment]
> @I-I-IT Incorrect. The whole point of LibreTube is that it uses the Piped API. When you disable the proxy _for videos_, the app still uses a Piped instance to attempt to load all the information required to start the videos: [libre-tube/LibreTube#6366 (comment)](https://github.com/libre-tube/LibreTube/issues/6366#issuecomment-2294846881).
> 
> You might be looking for something like [NewPipe](https://github.com/TeamNewPipe/NewPipe) instead. It works "offline."

well i didn't know the differences (in the backend) between libretube (and piped) and newpipe.
I guess as of now, i'll have both libretube (preffered) and newpipe as a backup cuz lately all the instances work like once or twice a day max... it's an imense chaos. I guess i could still use orbot or something to try cover up a little, at the expense of a slower connection...

**Comment by clarfonthey** [comment]
I know it's tempting to talk about workarounds as a user here, but ideally this issue's discussion should be mostly suggestions on which specific code change should be implemented to more generally fix this. A lot of them have been suggested here, specifically things done by the invidious team, but it's not clear which of them specifically would help here.

**Comment by Bnyro** [comment]
> I know it's tempting to talk about workarounds as a user here, but ideally this issue's discussion should be mostly suggestions on which specific code change should be implemented to more generally fix this. A lot of them have been suggested here, specifically things done by the invidious team, but it's not clear which of them specifically would help here.
>
There likely needs to be a fix at the NewPipe Extractor repository first, Piped doesn't have any logic to scrape YouTube information itself.

**Comment by candroid-man** [comment]
I am receiving this error on web and on mobile via LibreTube

**Comment by bellehop** [comment]
I am experiencing the issue too.
![Screenshot_20240829-135555~3](https://github.com/user-attachments/assets/0d89802c-d1eb-4939-a7fe-bead3264ac0c)

No video is working. Any solution would be helpful.

**Comment by voidplayer** [comment]
for now if you have your subscriptions working click on `share > youtube > newpipe`

If you dont, you can export your subscriptions to json and import them in [newpipe](https://f-droid.org/en/packages/org.schabi.newpipe/)

**Comment by B0pol** [comment]
Can we keep the button view on YouTube when this error happens please ?

**Comment by andriitrovg** [comment]
go to Settings -> Instance and enable Disable Piped proxy as well as Local streams extraction. Disclaimer: The bot-blocked API call will now be done directly from your IP address, which is obviously less privacy-friendly. Using a VPN is recommended, but might not always work since YouTube blocks IPs of VPN providers as well.

**Comment by andriitrovg** [comment]
go to Settings -> Instance and enable Disable Piped proxy as well as Local streams extraction. Disclaimer: The bot-blocked API call will now be done directly from your IP address, which is obviously less privacy-friendly. Using a VPN is recommended, but might not always work since YouTube blocks IPs of VPN providers as well.

**Comment by mpeter50** [comment]
Which instance do you use? We dont have such options (on piped.video, piped.projectsegfau.lt, piped.privacydev.net, piped.smnz.de, piped.adminforge.de).

Also, you have sent your comment doubly.

**Comment by lilwat1** [comment]
i am also getting this error even when signed in
i use librewolf and linux, all instances are the same but the one i use if of course piped.video
it's a shame because i can't use invidious due to it's abysmal speed! so realistically the only option that is left is regular youtube.

**Comment by lilwat1** [comment]
I only have two extensions on librewolf: dark reader and ublock origin. Disabling both and reloading changes the error message to: "IOS player response is not valid"

**Comment by voidplayer** [comment]
libretube is working again now too

**Comment by bonswouar** [comment]
@kubo6472 On (some) private instances, Piped still work, always.
If the IP is clean you shouldn't have any problem

**Comment by voidplayer** [comment]
Is it possible to add the video to a playlist despite having this error in the browser?

The button is not showing despite being able to load comments (and thus acknowledging the url is okay)

Should i open a separate bug for this?

**Comment by Bnyro** [comment]
That's the same issue, so no.

**Comment by MLGamer011** [comment]
Hey sorry if this is irrelevant, but I got this error...

org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "Sign in to confirm that you're not a bot"
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.checkPlayabilityStatus(YoutubeStreamExtractor.java:898)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:784)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:67)
	at me.kavin.piped.server.handlers.StreamHandlers.lambda$streamsResponse$0(StreamHandlers.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)

**Comment by nkfm200** [comment]
> Could you guys please stop commenting this issue with no new information, many people are following I guess and it's annoying to get useless notifications. If you've got the same problem _(and you probably do)_, just add a thumb up 👍 to the first post of this thread and hope & wait
> 
> _And if you wanna chat about workarounds or whatever, the matrix channel is still here_

hoping and waiting didn't do anything to solve this. i've tried all the instances and they're still down with the same error 🤨. where's the real solution?

**Comment by talon12431** [comment]
> > Could you guys please stop commenting this issue with no new information, many people are following I guess and it's annoying to get useless notifications. If you've got the same problem _(and you probably do)_, just add a thumb up 👍 to the first post of this thread and hope & wait
> > _And if you wanna chat about workarounds or whatever, the matrix channel is still here_
> 
> hoping and waiting didn't do anything to solve this. i've tried all the instances and they're still down with the same error 🤨. where's the real solution?

The real solution is for people to mass switch to a different video platform (Odysee, Peertube) and stop using google slopware, but that's never gonna happen

**Comment by DWolf-19** [comment]
Can we make Piped instance route all the requests over the Tor network? Or like optional feature on client-side (e.g  `Disable Piped proxy` & `Local stream extraction` in LibreTube but with Tor).

**Comment by MochyPei** [comment]
Same, i searched some youtube mirrors, and found Piped, and when i tried, i got this error, and even when i registered acccount, still getting same message.
![image](https://github.com/user-attachments/assets/40e94309-131f-4786-8721-c083ef03d029)

**Comment by DWolf-19** [comment]
Why my comment was marked as off-topic? I think it contains some new info/my guess about issue solving.

**Comment by VitoItalianGamer** [comment]
What piped instances are still working?

**Comment by aryaoffixial** [comment]
Will this **Spoof Streaming Data** patch work for Piped Too? I don't think anybody mentioned this before [Revanced Patches#3582](https://github.com/ReVanced/revanced-patches/pull/3582)

Revanced Extended working fine with this patch. I know piped using IOS spoofing too but revanced doesn't get "ios player response invalid" errors...

**Comment by bnjbvr** [comment]
Regarding previous comment: it seems [the code of piped-proxy supports](https://github.com/TeamPiped/piped-proxy/blob/main/src/main.rs#L103-L116) setting up a PROXY env variable to reroute external traffic to it. I've tried using an instance of https://github.com/kingcc/warproxy or https://github.com/cmj2002/warp-docker alongside the piped-proxy instance, then changed the docker-compose section for the piped-proxy to include `PROXY=warp:1080` in the env variable section, but it doesn't appear the traffic is getting routed through it. Am I missing something?

**Comment by 372405** [comment]
please fix it 
![image](https://github.com/user-attachments/assets/9aecfb9b-6413-48ad-83cc-2e7a295138c4)

**Comment by lilcheti** [comment]
Ok so which instances are working rn?

**Comment by mpeter50** [comment]
Those that you or your friends run for yourself. Public ones are being taken down by google.
Yeah it sucks, even so that now even Invidious has fallen.

My solution for the meantime has been to either not watch youtube, or if the video would be useful, I download it with yt-dlp. That way I also preserve it for when the video would become unavailable, as we all know thats the fate of a lot of videos on youtube, for various reasons.

**Comment by lilcheti** [comment]
So if it's working with warp we better start developing an api to run on cloudflare workers

**Comment by mpeter50** [comment]
I'm not familiar with Cloudflare's services, but I would expect that workers running youtube proxies would get shut down, maybe even with penalties for the owner account.

However, using CF Warp may be helpful in itself, but of course we will see if a larger instance starts to use it. [Apparently](https://libreddit.bus-hit.me/r/CloudFlare/comments/ldejnt/how_is_cloudflare_warp_different_from_a_vpn_what/k5x7fs5/?context=3#k5x7fs5) they are not forwarding the user's IP address to the destination anymore.
Does anyone know if a Piped/Invidious instance has tried doing this already?

---

Seeing the reactions to my previous comment, if anyong reading this is interested in downloading the videos for yourself, [here](https://gist.github.com/mpeter50/ff9285aa1a98866dea97e10f2b926acb) is the yt-dlp config file I use. I hope it will be useful.

**Comment by voidplayer** [comment]
would it be possible to add a local .js extractor as an option? libretube has the option to do the extraction locally and thats how they bypassed this issue

Yes, it gives away the privacy temporarly but it also makes more difficult/impossible to block

**Comment by lothar-cell** [comment]
I got the same issue recently.

**Comment by noodlejetski** [comment]
> I got the same issue recently.

might wanna read the recent replies before notifying everyone participating in the discussion.

**Comment by lothar-cell** [comment]
Yeah, I did what I understood, and changing instances didn't help.

**Comment by mrkrabs206** [comment]
No one wants to fix it, rather flood it

**Comment by RedrootDEV** [comment]
> No one wants to fix it, rather flood it

We would be very grateful to see how you fix it.

**Comment by 372405** [comment]
> > No one wants to fix it, rather flood it
> 
> We would be very grateful to see how you fix it.

how can I fix it if I do not know how to code that wall

**Comment by noodlejetski** [comment]
perhaps the issue could be locked to contributors only? I'm probably not the only one subscribed for notifications in case it gets resolved, and it's getting tiresome, getting all the "pls fix" comments in my email.

**Comment by mrkrabs206** [comment]
Not really

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 372405** [comment]
I have an idea why do you not youse chapshua
