### ISSUE TITLE
Video not available

### ISSUE THREAD

**Issue by AP2020C** [TeamPiped/Piped#3893]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I decided today to try Piped. I try two random videos and for both I get "Could not get any stream. See error variable to get further details.".
On youtube instead they see us correctly

### To Reproduce

Open https://piped.video/watch?v=t3gm0aWJgMA

### Expected behavior

Play the video

### Logs/Errors

org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:171)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:81)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:67)
	at me.kavin.piped.server.handlers.StreamHandlers.lambda$streamsResponse$0(StreamHandlers.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)

### Browser, and OS with Version.

Firefox 133 and Opera 114 on windows 10

**Comment by xxshady** [comment]
same here https://piped.video/watch?v=o1iqV5k6-QU

**Comment by Bnyro** [comment]
Duplicat of https://github.com/TeamPiped/Piped/issues/3658
