### ISSUE TITLE
Search functionality broken

### ISSUE THREAD

**Issue by tanyachaff** [TeamPiped/Piped#780]
Hello, when attempting to search for a video, the following appears in the search bar:

```
java.io.IOException: Received RST_STREAM: Protocol error at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source) at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source) at me.kavin.piped.utils.DownloaderImpl.executeRequest(DownloaderImpl.java:73) at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:197) at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2451) at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source) at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2449) at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2432) at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:107) at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:57) at me.kavin.piped.utils.DownloaderImpl.execute(DownloaderImpl.java:46) at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:70) at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:61) at me.kavin.piped.utils.ResponseHelper.suggestionsResponse(ResponseHelper.java:397) at me.kavin.piped.ServerLauncher.lambda$mainServlet$14(ServerLauncher.java:153) at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43) at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source) Caused by: java.io.IOException: Received RST_STREAM: Protocol error at java.net.http/jdk.internal.net.http.Stream.handleReset(Unknown Source) at java.net.http/jdk.internal.net.http.Stream.schedule(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source) at java.net.http/jdk.internal.net.http.Stream.receiveResetFrame(Unknown Source) at java.net.http/jdk.internal.net.http.Stream.incoming_reset(Unknown Source) at java.net.http/jdk.internal.net.http.Stream.otherFrame(Unknown Source) at java.net.http/jdk.internal.net.http.Stream.incoming(Unknown Source) at java.net.http/jdk.internal.net.http.Http2Connection.processFrame(Unknown Source) at java.net.http/jdk.internal.net.http.frame.FramesDecoder.decode(Unknown Source) at java.net.http/jdk.internal.net.http.Http2Connection$FramesController.processReceivedData(Unknown Source) at java.net.http/jdk.internal.net.http.Http2Connection.asyncReceive(Unknown Source) at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.processQueue(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source) at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.runOrSchedule(Unknown Source) at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Unknown Source) at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Unknown Source) at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(Unknown Source) at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(Unknown Source) at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(Unknown Source) at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(Unknown Source) at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source) at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(Unknown Source) at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(Unknown Source) at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(Unknown Source) at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source) at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source) ... 3 more 
```

Additionally, no results appear after pressing enter.

This may be due to new changes in YouTube's UI, [other clients are having similar problems](https://github.com/TeamNewPipe/NewPipe/issues/7734)

**Comment by FireMasterK** [comment]
This should've been fixed a few hours ago.
