### ISSUE TITLE
"This age-restricted video cannot be watched."

### ISSUE THREAD

**Issue by Mennaruuk** [TeamPiped/Piped#939]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Age-restricted videos cannot be accessed on Piped. The error that is raised is:

`This age-restricted video cannot be watched.`

### To Reproduce

1. Open the URL at https://piped.kavin.rocks/watch?v=EyubuR2QK4o
2. Note the error

### Expected behavior

Ideally, there should be a workaround for age-restricted videos. Whether there should be an age gate with a Yes or No button before a user visits is optional (and recommended IMO), but that's beside the point.

### Logs/Errors

```
org.schabi.newpipe.extractor.exceptions.AgeRestrictedContentException: This age-restricted video cannot be watched.
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.checkPlayabilityStatus(YoutubeStreamExtractor.java:765)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:716)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:60)
	at me.kavin.piped.utils.ResponseHelper.lambda$streamsResponse$0(ResponseHelper.java:70)
	at me.kavin.piped.utils.ResponseHelper$$Lambda$390/0x0000000000000000.get(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Browser, and OS with Version.

Mozilla Firefox 98.0.2
Microsoft Windows 10 21H1

### Additional context

It looks like a widespread issue. Invidious and yt-dlp have been suffering from the same problem, but they've [merged ](https://github.com/iv-org/invidious/pull/2996)[PRs ](https://github.com/yt-dlp/yt-dlp/pull/3233)for a new bypass method.

Thanks for your help.

**Comment by FireMasterK** [comment]
Issue at NewPipe: https://github.com/TeamNewPipe/NewPipe/issues/8102

**Comment by Cosipa** [comment]
Hi, I would like to add a comment, this issue was mentioned over on the invidious side and they fixed it, maybe we could use their fix for piped. Sorry, I can't share any links right now of it.
